name: Deploy Microbit Piano

on:
  push:
    branches: [ microbit-piano ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install & Build Microbit Piano
        run: |
          cd MicrobitPiano_2026
          npm install
          # 테마 패키지 직접 설치
          npm install @slidev/theme-default
          # 빌드 진행
          npx @slidev/cli build --base "/slidev/" --out "../dist"
          
          # SPA 라우터용 404.html 생성
          cp ../dist/index.html ../dist/404.html

      - uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - uses: actions/deploy-pages@v4